---
- name: Install application dependencies
  npm:
    path: /home/vagrant/userapi
    state: present
  become_user: vagrant

- name: Create systemd service file for User API
  template:
    src: userapi.service.j2
    dest: /etc/systemd/system/userapi.service
    mode: '0644'

- name: Reload systemd daemon
  systemd:
    daemon_reload: yes

- name: Start and enable User API service
  systemd:
    name: userapi
    state: started
    enabled: yes

- name: Wait for application to start
  wait_for:
    port: 3000
    delay: 3
    timeout: 30
